### ISSUE TITLE
How to process the raw audio in IEMOCAP?

### ISSUE THREAD

**Issue by FriedaSmith** [shamanez/BERT-like-is-All-You-Need#9]
How to process the raw audio in IEMOCAP? What does the naming format mean in the following picture? How is it generated?
![train_a](https://user-images.githubusercontent.com/64420430/108816352-ffd9d980-75f0-11eb-86ac-7eb1a4d6f86f.gif)

It contains a total of 5531 utterances among the 5 classes in IEMOCAP, but [what you provide](https://drive.google.com/drive/folders/1oiAiY0QgIpP3Wb9bPfC4hYdGrJ1MmDAP?usp=sharing) is only 5499. Can you upload the code for processing IEMOCAP?

**Comment by shamanez** [comment]
This is a naming conversion I used while I was chunking the emocap data into utterance.  The dataset contains 5 sessions, so "s_" is the session number. Then neu, hap, ang, sad and exc are the emotion cords for neutral, happy, sad anger, and excited.  I think I had to remove several examples, where their text modality or visual modality is corrupted, that's why I removed a few. 

Please use the following codebase to do the pre-processing. 

https://github.com/shamanez/MAIA-Data-Processing/tree/master/Preprocessing_scripts/iemocap

**Comment by FriedaSmith** [comment]
Thank you.
